name: graph_tool_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core Python
  - python=3.10
  - pip

  # Graph Tool & Visualization Dependencies
  - graph-tool=2.80
  - gtk3
  - pygobject
  - cairocffi

  # Data Science & Math
  - numpy=1.24.4
  - pandas=2.2.2
  - scipy=1.14.0
  - scikit-learn=1.5.1
  - pytorch=2.3.1
  - dask=2024.4.2
  - dask-expr=1.0.14
  - arrow=1.3.0
  - pyarrow=16.0.0

  # Graphing & Networks
  - networkx=3.3
  - leidenalg=0.10.2
  - python-igraph=0.11.4
  
  # Plotting
  - matplotlib=3.8.0
  - seaborn=0.13.2
  - wordcloud=1.9.3

  # Utilities
  - notebook=7.1.3
  - beautifulsoup4=4.12.3
  - regex=2024.5.15
  - zstandard=0.23.0

  # Pip packages
  - pip:
      - pysciebo==1.1.0